### ISSUE TITLE
Error while using in windows

### ISSUE THREAD

**Issue by ajithpadman** [valbok/lcov#1]
geninfo.perl: Unsuccessful stat on filename containing newline at D:\lcov-master\geninfo.perl line 927
geninfo.perl: Unsuccessful stat on filename containing newline at D:\lcov-master\geninfo.perl line 947.
geninfo.perl: ERROR: cannot write to directory

Generating html ...
The syntax of the command is incorrect.
genhtml.perl: ERROR: cannot create directory gcov/html/!

**Comment by valbok** [comment]
Hi Ajith,
looks like the filename happens to contain a newline character.
How did you get it?
Is it possible to reproduce? 
Do you have proper permissions in current dir to write?

**Comment by ajithpadman** [comment]
I dont think there can be some permission issues as I am running the cmd prompt in adminstrator mode. It is always reproducible

**Comment by valbok** [comment]
Ajith,
could you try to run following:

```
#!/usr/bin/perl -w

use Getopt::Long;
our $output_directory;
GetOptions("output-directory|o=s" => \$output_directory);
stat($output_directory);
```

Run like:

```
$ ./test.perl -o .
```

and see if newline appears?
if no newlines, maybe to put it to file and run it from another bat file?
The main question is how can it have newline or is it related to Getopt::Long.
Thanks

**Comment by valbok** [comment]
Anyway you could try to add chomp to lines 927 and 947 and also to genhtml.perl to check if it could help.
